# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxdNeQcHa20O5ZWU2pz3X1D6NYHzscLW
"""

val = float(input("Digite o valor da compra: "))
n50 = int(input("Digite a qtd de notas de R$50: "))
n20 = int(input("Digite a qtd de notas de R$20: "))
n10 = int(input("Digite a qtd de notas de R$10: "))
n5 = int(input("Digite a qtd de notas de R$5: "))

dinheiro = n50*50 + n20*20 + n10*10 + n5*5 #
troco = dinheiro - val

if troco > 0:
  print(f"A compra foi de R${val:.2f} o cliente forneceu R${dinheiro:.2f} e o troco é de R${troco:.2f}")
elif troco < 0:
  print(f" A compra foi de R${val:.2f} o cliente forneceu R${dinheiro:.2f} sendo insuficiente este valor")
else:
  print("Você forneceu o valor exato da compra!")

import math

x = float(input("Digite um número real: "))

if x >= 0: #se x for maior que 0 faça o que está a seguir
  y = math.sqrt(x) #math.sqrt() tira a raiz quadrada
  print("A raiz é: ",y)
else: #senão...caso contrario faça o que está a seguir
  print("Não existe raiz de número negativo")

#O objetivo agora é verificar

etanol = float(input("Digite o valor do etanol: "))
gas = float(input("Digite o valor da gasosa: "))
perc = 100*etanol/gas
print(f"Hoje o álcool está {perc:.2f}% da gasolina")

if perc > 70:
  print("Abasteça com gasolina")
else:
  print("Abasteça com etanol")